# Generated by Django 5.2.17 on 2026-08-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='ABC College of Engineering', max_length=200)),
                ('email', models.EmailField(default='admin@college.edu', max_length=254)),
                ('phone', models.CharField(default='9876543210', max_length=30)),
                ('notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
