# Generated by Django 5.2.17 on 2026-08-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('internal', 'Internal Exam'), ('midterm', 'Mid Term'), ('semester', 'Semester Exam'), ('practical', 'Practical Exam'), ('assignment', 'Assignment')], default='internal', max_length=30)),
                ('subject', models.CharField(max_length=150)),
                ('course', models.CharField(blank=True, max_length=150, null=True)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('passing_marks', models.PositiveIntegerField(default=40)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-exam_date', 'name'],
            },
        ),
    ]
