# Generated by Django 5.2.17 on 2026-08-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_default_academic_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField(default=1)),
                ('room', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
